#!/bin/bash

# Obtém a URL do remote origin
git_remote=$(git remote get-url origin 2>/dev/null)

# Verifica se o repositório foi encontrado
if [ -z "$git_remote" ]; then
    echo "Nenhum repositório Git configurado. Certifique-se de estar dentro de um repositório."
    exit 1
fi

# Define email e GPG Key conforme o repositório remoto
if [[ "$git_remote" =~ "github.com" ]]; then
    : "${GCFG_GITHUB_EMAIL:?Set GCFG_GITHUB_EMAIL}"
    : "${GCFG_GITHUB_GPG_KEY:?Set GCFG_GITHUB_GPG_KEY}"
    git config user.email "$GCFG_GITHUB_EMAIL"
    git config user.signingkey "$GCFG_GITHUB_GPG_KEY"
    echo "Configurado para GitHub."

elif [[ "$git_remote" =~ "gitlab.com" ]]; then
    : "${GCFG_GITLAB_EMAIL:?Set GCFG_GITLAB_EMAIL}"
    : "${GCFG_GITLAB_GPG_KEY:?Set GCFG_GITLAB_GPG_KEY}"
    git config user.email "$GCFG_GITLAB_EMAIL"
    git config user.signingkey "$GCFG_GITLAB_GPG_KEY"
    echo "Configurado para GitLab."

elif [[ "$git_remote" =~ "gitlab.company.com" ]]; then
    : "${GCFG_COMPANY_EMAIL:?Set GCFG_COMPANY_EMAIL}"
    : "${GCFG_COMPANY_GPG_KEY:?Set GCFG_COMPANY_GPG_KEY}"
    git config user.email "$GCFG_COMPANY_EMAIL"
    git config user.signingkey "$GCFG_COMPANY_GPG_KEY"
    echo "Configurado para GitLab Company."

else
    echo "Repositório remoto desconhecido: $git_remote"
    exit 1
fi

# Habilita assinatura automática de commits
git config commit.gpgsign true

echo "Configuração de Git e GPG Key concluída com sucesso!"
